/**
 * Enhanced Chatbot Database Schema
 * Supports multi-response pool, user memory profiles, and smart response selection
 */

-- ======================== RESPONSE POOL TABLE ========================
-- Stores multiple response variants for each intent/category
CREATE TABLE CHATBOT_RESPONSE_POOL (
  POOL_ID NUMBER PRIMARY KEY,
  INTENT_CATEGORY VARCHAR2(50) NOT NULL,
  RESPONSE_TYPE VARCHAR2(50) NOT NULL, -- 'SHORT', 'DETAILED', 'UPSELL', 'PERSONALIZED'
  RESPONSE_TEMPLATE CLOB NOT NULL,
  RESPONSE_RANK NUMBER DEFAULT 1, -- Priority rank (1 = highest)
  MIN_CONFIDENCE NUMBER(3,2) DEFAULT 0.5, -- Minimum confidence to use
  CONTEXT_TAGS VARCHAR2(200), -- e.g., "first_time,mobile,busy"
  USAGE_COUNT NUMBER DEFAULT 0,
  AVERAGE_RATING NUMBER(3,2) DEFAULT 0, -- 0-1, from user feedback
  CONVERSION_COUNT NUMBER DEFAULT 0, -- Times this response led to purchase
  IS_ACTIVE NUMBER DEFAULT 1,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
  CREATED_BY VARCHAR2(100),
  CONSTRAINT uq_pool_category_type UNIQUE (INTENT_CATEGORY, RESPONSE_TYPE)
);

CREATE INDEX idx_pool_category ON CHATBOT_RESPONSE_POOL(INTENT_CATEGORY);
CREATE INDEX idx_pool_type ON CHATBOT_RESPONSE_POOL(RESPONSE_TYPE);
CREATE INDEX idx_pool_rank ON CHATBOT_RESPONSE_POOL(RESPONSE_RANK);

-- ======================== RESPONSE SELECTION LOG ========================
-- Tracks which response was chosen and its performance
CREATE TABLE CHATBOT_RESPONSE_SELECTION_LOG (
  SELECTION_ID NUMBER PRIMARY KEY,
  MESSAGE_ID NUMBER NOT NULL,
  POOL_ID NUMBER NOT NULL,
  RESPONSE_TYPE VARCHAR2(50),
  SELECTION_REASON VARCHAR2(200), -- Why this response was chosen
  CONTEXT_FLAGS VARCHAR2(200), -- JSON flags used for selection
  USER_SENTIMENT_BEFORE VARCHAR2(50), -- optimistic, neutral, frustrated
  USER_SENTIMENT_AFTER VARCHAR2(50),
  WAS_HELPFUL NUMBER, -- 1: yes, -1: no, 0: not rated
  CONVERSION_RESULT NUMBER, -- 1: purchased, 0: no action
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT fk_log_message FOREIGN KEY (MESSAGE_ID) 
    REFERENCES CHATBOT_MESSAGES(MESSAGE_ID),
  CONSTRAINT fk_log_pool FOREIGN KEY (POOL_ID) 
    REFERENCES CHATBOT_RESPONSE_POOL(POOL_ID)
);

CREATE INDEX idx_log_message ON CHATBOT_RESPONSE_SELECTION_LOG(MESSAGE_ID);
CREATE INDEX idx_log_pool ON CHATBOT_RESPONSE_SELECTION_LOG(POOL_ID);
CREATE INDEX idx_log_helpful ON CHATBOT_RESPONSE_SELECTION_LOG(WAS_HELPFUL);
CREATE INDEX idx_log_conversion ON CHATBOT_RESPONSE_SELECTION_LOG(CONVERSION_RESULT);

-- ======================== USER PROFILE TABLE ========================
-- Enhanced user memory with detailed interaction history
CREATE TABLE CHATBOT_USER_PROFILE (
  PROFILE_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL UNIQUE,
  FULL_NAME VARCHAR2(100),
  PHONE VARCHAR2(20),
  EMAIL VARCHAR2(100),
  
  -- Preferences
  FAVORITE_CATEGORIES CLOB, -- JSON: [{category, frequency, last_mentioned_at}]
  FAVORITE_AUTHORS CLOB, -- JSON array
  PRICE_RANGE_MIN NUMBER,
  PRICE_RANGE_MAX NUMBER,
  BUDGET_TYPE VARCHAR2(50), -- 'BUDGET', 'REGULAR', 'PREMIUM'
  
  -- Interaction patterns
  INTERACTION_COUNT NUMBER DEFAULT 0,
  AVERAGE_RESPONSE_TIME NUMBER, -- How quickly user responds (seconds)
  PREFERRED_RESPONSE_TYPE VARCHAR2(50), -- 'SHORT', 'DETAILED', 'CONVERSATIONAL'
  USER_PERSONALITY VARCHAR2(50), -- 'DIRECT', 'CONVERSATIONAL', 'ANALYTICAL'
  
  -- Purchase behavior
  TOTAL_PURCHASES NUMBER DEFAULT 0,
  TOTAL_SPENT NUMBER DEFAULT 0,
  AVERAGE_ORDER_VALUE NUMBER,
  PURCHASE_FREQUENCY VARCHAR2(50), -- 'FREQUENT', 'OCCASIONAL', 'RARE'
  LAST_PURCHASE_DATE TIMESTAMP,
  DAYS_SINCE_LAST_PURCHASE NUMBER,
  
  -- Engagement
  IS_VIP NUMBER DEFAULT 0,
  CHURN_RISK NUMBER(3,2) DEFAULT 0, -- 0-1, likelihood of stopping engagement
  LIFETIME_VALUE NUMBER,
  
  -- Learning flags
  KNOWS_PAYMENT_METHODS NUMBER DEFAULT 0,
  KNOWS_SHIPPING NUMBER DEFAULT 0,
  KNOWS_REFUND_POLICY NUMBER DEFAULT 0,
  
  -- Metadata
  LAST_INTERACTION_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
  LAST_LEARNING_UPDATE TIMESTAMP
);

CREATE INDEX idx_profile_user ON CHATBOT_USER_PROFILE(USER_ID);
CREATE INDEX idx_profile_vip ON CHATBOT_USER_PROFILE(IS_VIP);
CREATE INDEX idx_profile_churn ON CHATBOT_USER_PROFILE(CHURN_RISK);

-- ======================== QUESTION VARIANTS TABLE ========================
-- Stores different ways users ask the same question
CREATE TABLE CHATBOT_QUESTION_VARIANTS (
  VARIANT_ID NUMBER PRIMARY KEY,
  INTENT_CATEGORY VARCHAR2(50) NOT NULL,
  QUESTION_TEXT VARCHAR2(500) NOT NULL,
  NORMALIZED_FORM VARCHAR2(500), -- Standardized version
  OCCURRENCE_COUNT NUMBER DEFAULT 1,
  SENTIMENT VARCHAR2(50), -- 'POSITIVE', 'NEUTRAL', 'NEGATIVE'
  IS_LEARNING_EXAMPLE NUMBER DEFAULT 1,
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
  UNIQUE (INTENT_CATEGORY, QUESTION_TEXT)
);

CREATE INDEX idx_variant_category ON CHATBOT_QUESTION_VARIANTS(INTENT_CATEGORY);
CREATE INDEX idx_variant_text ON CHATBOT_QUESTION_VARIANTS(QUESTION_TEXT);

-- ======================== CONVERSATION CONTEXT TABLE ========================
-- Detailed context for each conversation
CREATE TABLE CHATBOT_CONVERSATION_CONTEXT (
  CONTEXT_ID NUMBER PRIMARY KEY,
  CONVERSATION_ID NUMBER NOT NULL,
  DEVICE_TYPE VARCHAR2(50), -- 'MOBILE', 'DESKTOP', 'TABLET'
  ENTRY_POINT VARCHAR2(100), -- 'PRODUCT_PAGE', 'CHECKOUT', 'HOMEPAGE'
  TIME_OF_DAY VARCHAR2(50), -- 'MORNING', 'AFTERNOON', 'EVENING', 'NIGHT'
  USER_STATUS VARCHAR2(50), -- 'NEW', 'RETURNING', 'LOYAL', 'INACTIVE'
  PREVIOUS_PURCHASES NUMBER,
  IN_CART_VALUE NUMBER,
  PAGE_CONTEXT VARCHAR2(200), -- Current page user is on
  REFERRAL_SOURCE VARCHAR2(100),
  LAST_PAGE_VIEW TIMESTAMP,
  SESSION_DURATION_MS NUMBER,
  INTERACTION_PHASE VARCHAR2(50), -- 'DISCOVERY', 'CONSIDERATION', 'DECISION', 'SUPPORT'
  USER_URGENCY VARCHAR2(50), -- 'HIGH', 'MEDIUM', 'LOW'
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT fk_context_conv FOREIGN KEY (CONVERSATION_ID) 
    REFERENCES CHATBOT_CONVERSATIONS(CONVERSATION_ID)
);

CREATE INDEX idx_context_conv ON CHATBOT_CONVERSATION_CONTEXT(CONVERSATION_ID);
CREATE INDEX idx_context_urgency ON CHATBOT_CONVERSATION_CONTEXT(USER_URGENCY);

-- ======================== PERFORMANCE METRICS TABLE ========================
-- Analytics for chatbot performance
CREATE TABLE CHATBOT_PERFORMANCE_METRICS (
  METRIC_ID NUMBER PRIMARY KEY,
  METRIC_DATE DATE NOT NULL,
  INTENT_CATEGORY VARCHAR2(50),
  RESPONSE_TYPE VARCHAR2(50),
  
  -- Usage
  TOTAL_RESPONSES NUMBER DEFAULT 0,
  UNIQUE_USERS NUMBER DEFAULT 0,
  
  -- Quality
  AVERAGE_SATISFACTION NUMBER(3,2),
  HELPFUL_COUNT NUMBER DEFAULT 0,
  NOT_HELPFUL_COUNT NUMBER DEFAULT 0,
  
  -- Business
  CONVERSION_COUNT NUMBER DEFAULT 0,
  CONVERSION_RATE NUMBER(5,4),
  REVENUE_GENERATED NUMBER,
  
  -- Performance
  AVERAGE_RESPONSE_TIME_MS NUMBER,
  
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT uq_metric_date_category UNIQUE (METRIC_DATE, INTENT_CATEGORY, RESPONSE_TYPE)
);

CREATE INDEX idx_metric_date ON CHATBOT_PERFORMANCE_METRICS(METRIC_DATE);
CREATE INDEX idx_metric_category ON CHATBOT_PERFORMANCE_METRICS(INTENT_CATEGORY);

-- ======================== SEQUENCES ========================
CREATE SEQUENCE chatbot_pool_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE chatbot_selection_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE chatbot_profile_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE chatbot_variant_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE chatbot_context_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE chatbot_metric_seq START WITH 1 INCREMENT BY 1 INCREMENT BY 1 NOCACHE NOCYCLE;
