-- ============================================
-- REVIEW & WISHLIST SYSTEM
-- ============================================

-- 1. PRODUCT REVIEWS TABLE
CREATE TABLE PRODUCT_REVIEWS (
  REVIEW_ID NUMBER PRIMARY KEY,
  PRODUCT_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  RATING NUMBER(2,1) NOT NULL CHECK (RATING >= 1 AND RATING <= 5),
  TITLE VARCHAR2(255),
  CONTENT CLOB,
  VERIFIED_PURCHASE NUMBER(1) DEFAULT 0,
  HELPFUL_COUNT NUMBER DEFAULT 0,
  UNHELPFUL_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(20) DEFAULT 'PUBLISHED',
  SENTIMENT VARCHAR2(20),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PRODUCT_ID) REFERENCES SANPHAM(MASP),
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 2. REVIEW IMAGES TABLE
CREATE TABLE REVIEW_IMAGES (
  IMAGE_ID NUMBER PRIMARY KEY,
  REVIEW_ID NUMBER NOT NULL,
  IMAGE_URL VARCHAR2(500),
  DISPLAY_ORDER NUMBER,
  UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REVIEW_ID) REFERENCES PRODUCT_REVIEWS(REVIEW_ID) ON DELETE CASCADE
);

-- 3. REVIEW LIKES TABLE
CREATE TABLE REVIEW_LIKES (
  LIKE_ID NUMBER PRIMARY KEY,
  REVIEW_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  LIKE_TYPE VARCHAR2(10) CHECK (LIKE_TYPE IN ('HELPFUL', 'UNHELPFUL')),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (REVIEW_ID, USER_ID, LIKE_TYPE),
  FOREIGN KEY (REVIEW_ID) REFERENCES PRODUCT_REVIEWS(REVIEW_ID) ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 4. REVIEW REPORTS TABLE
CREATE TABLE REVIEW_REPORTS (
  REPORT_ID NUMBER PRIMARY KEY,
  REVIEW_ID NUMBER NOT NULL,
  REPORTER_ID NUMBER NOT NULL,
  REASON VARCHAR2(255),
  DESCRIPTION CLOB,
  STATUS VARCHAR2(20) DEFAULT 'PENDING',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  RESOLVED_AT TIMESTAMP,
  FOREIGN KEY (REVIEW_ID) REFERENCES PRODUCT_REVIEWS(REVIEW_ID) ON DELETE CASCADE,
  FOREIGN KEY (REPORTER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- 5. PRODUCT REVIEW SUMMARY (Cached AI Insights)
CREATE TABLE PRODUCT_REVIEW_SUMMARY (
  SUMMARY_ID NUMBER PRIMARY KEY,
  PRODUCT_ID NUMBER NOT NULL UNIQUE,
  AVERAGE_RATING NUMBER(3,2),
  TOTAL_REVIEWS NUMBER,
  RATING_DISTRIBUTION CLOB,
  AI_SUMMARY CLOB,
  POSITIVE_PERCENT NUMBER(5,2),
  NEUTRAL_PERCENT NUMBER(5,2),
  NEGATIVE_PERCENT NUMBER(5,2),
  KEY_STRENGTHS CLOB,
  KEY_WEAKNESSES CLOB,
  LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PRODUCT_ID) REFERENCES SANPHAM(MASP)
);

-- 6. ENHANCED WISHLIST TABLE (Expand existing)
-- Assuming USER_WISHLIST already exists, add new columns if needed
-- ALTER TABLE USER_WISHLIST ADD (
--   PRICE_ALERT NUMBER(1) DEFAULT 0,
--   PRICE_ALERT_THRESHOLD NUMBER(10,2),
--   ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--   STOCK_ALERT NUMBER(1) DEFAULT 1
-- );

-- 7. PRICE CHANGE NOTIFICATIONS
CREATE TABLE PRICE_CHANGE_NOTIFICATIONS (
  NOTIFICATION_ID NUMBER PRIMARY KEY,
  WISHLIST_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  OLD_PRICE NUMBER(10,2),
  NEW_PRICE NUMBER(10,2),
  DISCOUNT_PERCENT NUMBER(5,2),
  STATUS VARCHAR2(20) DEFAULT 'PENDING',
  SENT_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (WISHLIST_ID) REFERENCES USER_WISHLIST(WISHLIST_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES SANPHAM(MASP)
);

-- 8. STOCK NOTIFICATIONS
CREATE TABLE STOCK_NOTIFICATIONS (
  NOTIFICATION_ID NUMBER PRIMARY KEY,
  WISHLIST_ID NUMBER NOT NULL,
  PRODUCT_ID NUMBER NOT NULL,
  OLD_STOCK NUMBER,
  NEW_STOCK NUMBER,
  STATUS VARCHAR2(20) DEFAULT 'PENDING',
  SENT_AT TIMESTAMP,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (WISHLIST_ID) REFERENCES USER_WISHLIST(WISHLIST_ID),
  FOREIGN KEY (PRODUCT_ID) REFERENCES SANPHAM(MASP)
);

-- ============================================
-- SEQUENCES
-- ============================================

CREATE SEQUENCE SEQ_REVIEW_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_IMAGE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_LIKE_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_REVIEW_REPORT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SUMMARY_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRICE_NOTIFICATION_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_NOTIFICATION_ID START WITH 1 INCREMENT BY 1;

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IDX_REVIEW_PRODUCT ON PRODUCT_REVIEWS(PRODUCT_ID);
CREATE INDEX IDX_REVIEW_USER ON PRODUCT_REVIEWS(USER_ID);
CREATE INDEX IDX_REVIEW_RATING ON PRODUCT_REVIEWS(RATING);
CREATE INDEX IDX_REVIEW_STATUS ON PRODUCT_REVIEWS(STATUS);
CREATE INDEX IDX_REVIEW_SENTIMENT ON PRODUCT_REVIEWS(SENTIMENT);
CREATE INDEX IDX_REVIEW_CREATED ON PRODUCT_REVIEWS(CREATED_AT);
CREATE INDEX IDX_REVIEW_HELPFUL ON PRODUCT_REVIEWS(HELPFUL_COUNT DESC);

CREATE INDEX IDX_REVIEW_IMAGE_REVIEW ON REVIEW_IMAGES(REVIEW_ID);
CREATE INDEX IDX_REVIEW_LIKE_REVIEW ON REVIEW_LIKES(REVIEW_ID);
CREATE INDEX IDX_REVIEW_LIKE_USER ON REVIEW_LIKES(USER_ID);
CREATE INDEX IDX_REVIEW_REPORT_REVIEW ON REVIEW_REPORTS(REVIEW_ID);
CREATE INDEX IDX_REVIEW_REPORT_STATUS ON REVIEW_REPORTS(STATUS);

CREATE INDEX IDX_SUMMARY_PRODUCT ON PRODUCT_REVIEW_SUMMARY(PRODUCT_ID);
CREATE INDEX IDX_PRICE_NOTIF_WISHLIST ON PRICE_CHANGE_NOTIFICATIONS(WISHLIST_ID);
CREATE INDEX IDX_STOCK_NOTIF_WISHLIST ON STOCK_NOTIFICATIONS(WISHLIST_ID);

-- ============================================
-- TRIGGERS (Optional - for audit)
-- ============================================

-- Update UPDATED_AT timestamp automatically
CREATE OR REPLACE TRIGGER TRG_REVIEW_UPDATE
BEFORE UPDATE ON PRODUCT_REVIEWS
FOR EACH ROW
BEGIN
  :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SUMMARY_UPDATE
BEFORE UPDATE ON PRODUCT_REVIEW_SUMMARY
FOR EACH ROW
BEGIN
  :NEW.LAST_UPDATED := CURRENT_TIMESTAMP;
END;
/

COMMIT;
