/**
 * User Profile Enhancement Schema
 * Extends existing database with profile analytics, insights, and personalization
 */

-- ======================== USER ANALYTICS TABLE ========================
-- Track user behavior and reading patterns
CREATE TABLE USER_READING_ANALYTICS (
  ANALYTIC_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL UNIQUE,
  
  -- Reading stats
  TOTAL_BOOKS_VIEWED NUMBER DEFAULT 0,
  TOTAL_BOOKS_PURCHASED NUMBER DEFAULT 0,
  TOTAL_BOOKS_REVIEWED NUMBER DEFAULT 0,
  TOTAL_SPENT NUMBER DEFAULT 0,
  AVERAGE_SPENDING NUMBER,
  
  -- Category preferences
  FAVORITE_CATEGORY_1 VARCHAR2(100),
  FAVORITE_CATEGORY_1_COUNT NUMBER DEFAULT 0,
  FAVORITE_CATEGORY_2 VARCHAR2(100),
  FAVORITE_CATEGORY_2_COUNT NUMBER DEFAULT 0,
  FAVORITE_CATEGORY_3 VARCHAR2(100),
  FAVORITE_CATEGORY_3_COUNT NUMBER DEFAULT 0,
  
  -- Reading behavior
  AVERAGE_RATING_GIVEN NUMBER(3,2),
  REVIEW_COUNT NUMBER DEFAULT 0,
  WISHLIST_COUNT NUMBER DEFAULT 0,
  
  -- Activity patterns
  LAST_PURCHASE_DATE TIMESTAMP,
  DAYS_SINCE_PURCHASE NUMBER,
  PEAK_ACTIVITY_DAY VARCHAR2(20), -- e.g., "MONDAY", "WEEKEND"
  PEAK_ACTIVITY_HOUR NUMBER(2),   -- 0-23
  AVERAGE_SESSION_DURATION_MINUTES NUMBER,
  
  -- Reading preferences (AI-analyzed)
  PREFERRED_DIFFICULTY VARCHAR2(50), -- Analyzed from purchases
  READING_SPEED VARCHAR2(50),        -- FAST, SLOW, MIXED (analyzed)
  PREFERS_EBOOKS NUMBER DEFAULT 0,
  PREFERS_PHYSICAL NUMBER DEFAULT 0,
  
  -- Engagement
  IS_ACTIVE NUMBER DEFAULT 1,
  CHURN_RISK NUMBER(3,2) DEFAULT 0, -- 0-1
  LIFETIME_VALUE NUMBER,
  ENGAGEMENT_SCORE NUMBER(3,2),     -- 0-1
  
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT fk_analytics_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID)
);

CREATE INDEX idx_analytics_user ON USER_READING_ANALYTICS(USER_ID);
CREATE INDEX idx_analytics_category ON USER_READING_ANALYTICS(FAVORITE_CATEGORY_1);

-- ======================== USER LOGIN HISTORY ========================
-- Track login activity and security
CREATE TABLE USER_LOGIN_HISTORY (
  LOGIN_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL,
  
  LOGIN_TIME TIMESTAMP DEFAULT SYSDATE,
  IP_ADDRESS VARCHAR2(45),
  DEVICE_TYPE VARCHAR2(50),        -- 'MOBILE', 'DESKTOP', 'TABLET'
  BROWSER_NAME VARCHAR2(100),
  BROWSER_VERSION VARCHAR2(50),
  
  LOGIN_STATUS VARCHAR2(50),       -- 'SUCCESS', 'FAILED', 'BLOCKED'
  FAILURE_REASON VARCHAR2(200),    -- If failed
  
  SESSION_DURATION_MINUTES NUMBER,
  LAST_ACTIVITY TIMESTAMP,
  
  CONSTRAINT fk_login_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID)
);

CREATE INDEX idx_login_user ON USER_LOGIN_HISTORY(USER_ID);
CREATE INDEX idx_login_date ON USER_LOGIN_HISTORY(LOGIN_TIME DESC);
CREATE INDEX idx_login_status ON USER_LOGIN_HISTORY(LOGIN_STATUS);

-- ======================== USER SECURITY SETTINGS ========================
-- Enhanced security options
CREATE TABLE USER_SECURITY_SETTINGS (
  SECURITY_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL UNIQUE,
  
  -- 2FA
  TWO_FA_ENABLED NUMBER DEFAULT 0,
  TWO_FA_METHOD VARCHAR2(50),      -- 'EMAIL', 'SMS', 'AUTHENTICATOR'
  TWO_FA_SECRET VARCHAR2(200),     -- For TOTP
  TWO_FA_LAST_VERIFIED TIMESTAMP,
  
  -- Password
  PASSWORD_LAST_CHANGED TIMESTAMP,
  PASSWORD_CHANGE_REQUIRED NUMBER DEFAULT 0,
  FAILED_LOGIN_ATTEMPTS NUMBER DEFAULT 0,
  ACCOUNT_LOCKED_UNTIL TIMESTAMP,
  
  -- Privacy
  PROFILE_VISIBILITY VARCHAR2(50),   -- 'PUBLIC', 'FRIENDS_ONLY', 'PRIVATE'
  SHOW_PURCHASE_HISTORY NUMBER DEFAULT 0,
  SHOW_READING_PREFERENCES NUMBER DEFAULT 0,
  
  -- Notifications
  EMAIL_NOTIFICATIONS_ENABLED NUMBER DEFAULT 1,
  SMS_NOTIFICATIONS_ENABLED NUMBER DEFAULT 0,
  RECOMMENDATION_EMAILS NUMBER DEFAULT 1,
  ORDER_UPDATE_EMAILS NUMBER DEFAULT 1,
  
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINT fk_security_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID)
);

CREATE INDEX idx_security_user ON USER_SECURITY_SETTINGS(USER_ID);

-- ======================== USER WISHLIST ========================
-- Books user wants to read/buy
CREATE TABLE USER_WISHLIST (
  WISHLIST_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL,
  MASP VARCHAR2(50) NOT NULL,
  
  PRIORITY VARCHAR2(50),           -- 'HIGH', 'MEDIUM', 'LOW'
  ADDED_DATE TIMESTAMP DEFAULT SYSDATE,
  REASON CLOB,                     -- Why they want it
  REMINDER_SET_DATE TIMESTAMP,     -- When they set reminder for price drop
  TARGET_PRICE NUMBER,             -- Notify if drops below
  
  IS_ACTIVE NUMBER DEFAULT 1,
  PURCHASED_DATE TIMESTAMP,        -- If they bought it
  
  CONSTRAINT fk_wishlist_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID),
  CONSTRAINT fk_wishlist_product FOREIGN KEY (MASP) 
    REFERENCES SANPHAM(MASP),
  CONSTRAINT uq_wishlist_user_product UNIQUE (USER_ID, MASP)
);

CREATE INDEX idx_wishlist_user ON USER_WISHLIST(USER_ID);
CREATE INDEX idx_wishlist_active ON USER_WISHLIST(IS_ACTIVE);
CREATE INDEX idx_wishlist_priority ON USER_WISHLIST(PRIORITY);

-- ======================== USER REVIEWS ========================
-- User book reviews (if not already in SANPHAM comments)
CREATE TABLE USER_BOOK_REVIEWS (
  REVIEW_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL,
  MASP VARCHAR2(50) NOT NULL,
  
  RATING NUMBER(3,2),              -- 1-5 stars
  REVIEW_TITLE VARCHAR2(255),
  REVIEW_TEXT CLOB,
  
  HELPFUL_COUNT NUMBER DEFAULT 0,
  UNHELPFUL_COUNT NUMBER DEFAULT 0,
  
  REVIEW_DATE TIMESTAMP DEFAULT SYSDATE,
  UPDATED_DATE TIMESTAMP,
  
  IS_VERIFIED_PURCHASE NUMBER DEFAULT 0,
  IS_APPROVED NUMBER DEFAULT 1,
  
  CONSTRAINT fk_review_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID),
  CONSTRAINT fk_review_product FOREIGN KEY (MASP) 
    REFERENCES SANPHAM(MASP),
  CONSTRAINT uq_review_user_product UNIQUE (USER_ID, MASP)
);

CREATE INDEX idx_review_user ON USER_BOOK_REVIEWS(USER_ID);
CREATE INDEX idx_review_product ON USER_BOOK_REVIEWS(MASP);
CREATE INDEX idx_review_rating ON USER_BOOK_REVIEWS(RATING DESC);
CREATE INDEX idx_review_date ON USER_BOOK_REVIEWS(REVIEW_DATE DESC);

-- ======================== USER PROFILE SECTIONS ========================
-- Track user's profile completeness
CREATE TABLE USER_PROFILE_COMPLETENESS (
  PROFILE_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL UNIQUE,
  
  -- Completion tracking
  BASIC_INFO_COMPLETE NUMBER DEFAULT 0,      -- Name, email, phone
  ADDRESS_COMPLETE NUMBER DEFAULT 0,
  AVATAR_UPLOADED NUMBER DEFAULT 0,
  PREFERENCES_SET NUMBER DEFAULT 0,
  REVIEWS_WRITTEN NUMBER DEFAULT 0,
  
  OVERALL_COMPLETENESS_PERCENT NUMBER(3,1) DEFAULT 0,
  
  LAST_SECTION_VIEWED VARCHAR2(100),
  LAST_UPDATE TIMESTAMP DEFAULT SYSDATE,
  
  CONSTRAINT fk_profile_comp_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID)
);

CREATE INDEX idx_profile_comp_user ON USER_PROFILE_COMPLETENESS(USER_ID);

-- ======================== USER NOTIFICATIONS ========================
-- Smart notifications for users
CREATE TABLE USER_NOTIFICATIONS (
  NOTIFICATION_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL,
  
  NOTIFICATION_TYPE VARCHAR2(100),  -- 'RECOMMENDATION', 'PRICE_DROP', 'NEW_RELEASE', etc
  TITLE VARCHAR2(255),
  MESSAGE CLOB,
  RELATED_MASP VARCHAR2(50),        -- Book ID if applicable
  
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  READ_AT TIMESTAMP,
  CLICKED_AT TIMESTAMP,
  
  ACTION_URL VARCHAR2(500),         -- URL if user clicks
  
  IS_READ NUMBER DEFAULT 0,
  IS_DELETED NUMBER DEFAULT 0,
  
  CONSTRAINT fk_notif_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID),
  CONSTRAINT fk_notif_product FOREIGN KEY (RELATED_MASP) 
    REFERENCES SANPHAM(MASP)
);

CREATE INDEX idx_notif_user ON USER_NOTIFICATIONS(USER_ID);
CREATE INDEX idx_notif_read ON USER_NOTIFICATIONS(IS_READ);
CREATE INDEX idx_notif_created ON USER_NOTIFICATIONS(CREATED_AT DESC);

-- ======================== USER AI INSIGHTS ========================
-- Cache AI-generated insights about user
CREATE TABLE USER_AI_INSIGHTS (
  INSIGHT_ID NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(50) NOT NULL UNIQUE,
  
  -- Reading style insights
  READING_STYLE VARCHAR2(200),      -- e.g., "Bạn thích đọc sách ngắn, dễ hiểu"
  FAVORITE_GENRE_INSIGHT VARCHAR2(200),
  READING_PACE_INSIGHT VARCHAR2(200),
  
  -- Behavior insights
  ACTIVITY_PATTERN VARCHAR2(200),   -- e.g., "Hoạt động nhiều vào cuối tuần"
  PEAK_TIME_INSIGHT VARCHAR2(200),
  SPENDING_PATTERN VARCHAR2(200),
  
  -- Recommendations insight
  RECOMMENDATION_REASON VARCHAR2(500),
  
  -- Generated insights (JSON array)
  ALL_INSIGHTS CLOB,               -- JSON array of various insights
  
  INSIGHT_CONFIDENCE NUMBER(3,2),  -- 0-1, how confident are we
  GENERATED_AT TIMESTAMP DEFAULT SYSDATE,
  NEXT_UPDATE TIMESTAMP,
  
  CONSTRAINT fk_insight_user FOREIGN KEY (USER_ID) 
    REFERENCES USERS(USER_ID)
);

CREATE INDEX idx_insight_user ON USER_AI_INSIGHTS(USER_ID);
CREATE INDEX idx_insight_generated ON USER_AI_INSIGHTS(GENERATED_AT);

-- ======================== SEQUENCES ========================
CREATE SEQUENCE user_analytics_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_login_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_security_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_wishlist_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_review_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_profile_comp_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_notification_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE user_insight_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
