/**
 * Oracle Database Schema for VNPay Integration
 * Run this script to create payment-related tables
 */

-- Drop existing tables (if needed)
-- DROP TABLE REFUND_REQUESTS;
-- DROP TABLE PAYMENT_TRANSACTIONS;
-- DROP SEQUENCE refund_seq;
-- DROP SEQUENCE payment_transaction_seq;

-- Create sequences
CREATE SEQUENCE payment_transaction_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE refund_seq
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Payment Transactions Table
CREATE TABLE PAYMENT_TRANSACTIONS (
  TRANSACTION_ID VARCHAR2(100) PRIMARY KEY,
  ORDER_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  AMOUNT NUMBER(10,2) NOT NULL,
  STATUS VARCHAR2(50), -- PENDING, SUCCESS, FAILED, CANCELLED
  RESPONSE_CODE VARCHAR2(10),
  PAYMENT_METHOD VARCHAR2(50), -- VNPAY, COD, etc.
  TRANSACTION_NO VARCHAR2(100),
  BANK_CODE VARCHAR2(50),
  BANK_TRAN_NO VARCHAR2(100),
  CARD_TYPE VARCHAR2(50),
  PAY_DATE VARCHAR2(14), -- YYYYMMDDHHmmss
  TRANSACTION_DATA CLOB, -- Stores full response from VNPay
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
  CONSTRAINTS fk_transaction_order 
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
  CONSTRAINTS fk_transaction_user 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create indexes on PAYMENT_TRANSACTIONS
CREATE INDEX idx_payment_order ON PAYMENT_TRANSACTIONS(ORDER_ID);
CREATE INDEX idx_payment_user ON PAYMENT_TRANSACTIONS(USER_ID);
CREATE INDEX idx_payment_status ON PAYMENT_TRANSACTIONS(STATUS);
CREATE INDEX idx_payment_created ON PAYMENT_TRANSACTIONS(CREATED_AT);

-- Refund Requests Table
CREATE TABLE REFUND_REQUESTS (
  REFUND_ID NUMBER PRIMARY KEY,
  TRANSACTION_ID VARCHAR2(100) NOT NULL,
  ORDER_ID NUMBER NOT NULL,
  AMOUNT NUMBER(10,2) NOT NULL,
  REASON VARCHAR2(500),
  STATUS VARCHAR2(50), -- PENDING, APPROVED, REJECTED, COMPLETED
  RESPONSE_CODE VARCHAR2(10),
  REFUND_TRANSACTION_NO VARCHAR2(100),
  NOTES VARCHAR2(1000),
  CREATED_AT TIMESTAMP DEFAULT SYSDATE,
  UPDATED_AT TIMESTAMP DEFAULT SYSDATE,
  COMPLETED_AT TIMESTAMP,
  CONSTRAINTS fk_refund_transaction 
    FOREIGN KEY (TRANSACTION_ID) REFERENCES PAYMENT_TRANSACTIONS(TRANSACTION_ID),
  CONSTRAINTS fk_refund_order 
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

-- Create indexes on REFUND_REQUESTS
CREATE INDEX idx_refund_transaction ON REFUND_REQUESTS(TRANSACTION_ID);
CREATE INDEX idx_refund_order ON REFUND_REQUESTS(ORDER_ID);
CREATE INDEX idx_refund_status ON REFUND_REQUESTS(STATUS);

-- Add payment-related columns to ORDERS table if not exists
-- ALTER TABLE ORDERS ADD PAYMENT_METHOD VARCHAR2(50);
-- ALTER TABLE ORDERS ADD UPDATED_AT TIMESTAMP DEFAULT SYSDATE;

-- Sample data for testing
-- INSERT INTO PAYMENT_TRANSACTIONS VALUES (
--   'TEST_001_' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
--   1, 1, 500000, 'PENDING', NULL, 'VNPAY', NULL, NULL, NULL, NULL, NULL, NULL, SYSDATE, SYSDATE
-- );

COMMIT;
